const cars=[
['NEON RX-7','ROTARY ICON','#ff2f9e',3.2,86,92,78,74,'STREET'],['SPECTER R','JDM COUPE','#20e5ff',3,91,84,82,78,'ELITE'],['VORTEX GT','V8 MUSCLE','#ff9a3c',3.4,95,68,66,88,'STREET'],['MIAMI XS','SPORT COMPACT','#d5ff3f',3.5,81,96,91,70,'ELITE'],['NOVA S','EURO STREET','#a879ff',3.1,84,89,86,82,'ELITE'],['BLAZE X','TWIN TURBO','#ff5646',2.9,88,80,73,94,'EXOTIC'],['MIDNIGHT CBR','STREET SPEC','#5f9bff',3.3,79,94,85,84,'ELITE'],['PHANTOM 8','V8 SUPERCAR','#d7d9dd',2.8,92,87,79,91,'EXOTIC'],['HEATWAVE','STREET ROCKET','#ffcf4a',3,87,90,81,86,'EXOTIC'],['NIGHTFALL','HYPER GT','#8cf3d6',2.6,97,93,94,96,'LEGEND']];
const rivals=[['BLACKOUT','SUPRA','#111722',82,76],['NITRO RICO','GT-R','#19365b',85,80],['JAX','COBRA','#a7193c',88,73],['MIKA','EVO X','#555b68',90,82]],tracks=['BAYVIEW STRIP','OCEAN DRIVE','PALM ISLAND','NEON CAUSEWAY','MIDNIGHT MARINA','SUNSET BLVD','VICE DISTRICT','LITTLE HAVANA','SKYLINE EXPRESS','COASTLINE CLASH','NIGHT MARKET','GOLD COAST','MIRROR LAKE','LAST CALL','AFTERGLOW','FINAL RUN'];
const S={car:0,level:1,credits:2500,gear:1,rpm:8,nitro:100,player:0,rival:0,time:0,perfect:0,running:false};const $=id=>document.getElementById(id);let canvas=$('raceCanvas'),ctx=canvas.getContext('2d'),last=0;
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function renderCars(){$('carList').innerHTML=cars.map((c,i)=>`<div class="car-row ${i===S.car?'active':''}" data-car="${i}"><span class="car-number">${String(i+1).padStart(2,'0')}</span><span class="mini-car" style="--c:${c[2]}"></span><div><h3>${c[0]}</h3><small>${c[1]}</small></div><span class="car-score">${c[3].toFixed(1)}</span></div>`).join('');document.querySelectorAll('.car-row').forEach(x=>x.onclick=()=>selectCar(+x.dataset.car))}
function selectCar(i){S.car=i;document.querySelectorAll('.car-row').forEach((x,n)=>x.classList.toggle('active',n===i));let c=cars[i];$('selectedName').textContent=c[0];$('selectedRarity').textContent=c[8];$('carIndex').textContent=`${String(i+1).padStart(2,'0')} / 10`;$('statAccel').textContent=c[3].toFixed(1);['Launch','Shift','Grip','Nitro'].forEach((n,j)=>$('bar'+n).style.width=c[4+j]+'%');$('tuneNote').textContent='A '+c[1].toLowerCase()+' tuned for aggressive night runs.';let a=$('carArt');a.style.setProperty('--car',c[2]);a.style.setProperty('--car-glow',c[2]+'66');a.innerHTML='<div class="body"></div><div class="roof"></div><div class="glass"></div><div class="spoiler"></div><div class="lamp a"></div><div class="lamp b"></div><div class="wheel a"></div><div class="wheel b"></div>'}
function setup(){let c=cars[S.car],r=rivals[(S.level-1)%4];$('eventName').textContent=`${tracks[S.level-1]} // LEVEL ${String(S.level).padStart(2,'0')}`;$('levelNo').textContent=String(S.level).padStart(2,'0');$('trackName').textContent=tracks[S.level-1];$('youName').textContent=c[0];$('youPower').textContent=c[4];$('youGrip').textContent=c[6];$('rivalName').textContent=`${r[0]} // ${r[1]}`;$('rivalCar').textContent=r[0];$('rivalPower').textContent=r[3];$('rivalGrip').textContent=r[4];$('distanceValue').textContent='0 M';$('gearValue').textContent='1';$('rpmValue').textContent='0.8';$('raceMessage').textContent='GET READY';document.querySelectorAll('.starting-lights i').forEach(x=>x.className='');$('playerProgress').style.width=$('rivalProgress').style.width='0%'}
function startRace(){Object.assign(S,{gear:1,rpm:8,nitro:100,player:0,rival:0,time:0,perfect:0,running:false});setup();show('race');let cd=$('countdown'),msg=$('raceMessage'),ls=[...document.querySelectorAll('.starting-lights i')],n=3;cd.style.opacity=1;cd.style.color='white';cd.textContent=n;let t=setInterval(()=>{if(n){ls[3-n].className='on';n--;cd.textContent=n||'GO';if(!n){ls.forEach(x=>x.className='go');msg.textContent='GO!';cd.style.color='var(--lime)'}}else{clearInterval(t);setTimeout(()=>{cd.style.opacity=0;msg.textContent='SHIFT AT THE RIGHT TIME';S.running=true;S.start=performance.now()},220)}},620)}
function shift(){if(!S.running)return;let p=S.rpm,g=7+S.gear*2.5,q='GOOD SHIFT';if(p>=72&&p<=82){g*=1.45;q='PERFECT SHIFT';S.perfect++}else if(p>92){g*=.6;q='BOUNCER'}else if(p<52){g*=.78;q='EARLY SHIFT'}g*=cars[S.car][4]/85;S.player+=g;S.gear=Math.min(6,S.gear+1);S.rpm=35;toast(q)}
function nitro(){if(!S.running||S.nitro<8)return;S.nitro-=28;S.player+=13+cars[S.car][7]/12;toast('NITRO BOOST')}
function toast(t){let e=$('raceToast');e.textContent=t;e.style.opacity=1;e.animate([{opacity:0,transform:'translate(-50%,15px)'},{opacity:1,transform:'translate(-50%,0)'},{opacity:0,transform:'translate(-50%,-15px)'}],{duration:850})}
function resize(){let d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}
function car(x,y,s,col,player){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.shadowColor=col;ctx.shadowBlur=player?28:18;ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(-78,25);ctx.lineTo(-68,5);ctx.lineTo(-42,-4);ctx.lineTo(-20,-23);ctx.lineTo(36,-22);ctx.lineTo(59,-7);ctx.lineTo(78,9);ctx.lineTo(67,28);ctx.lineTo(-67,29);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#080a10';ctx.beginPath();ctx.moveTo(-25,-5);ctx.lineTo(-13,-21);ctx.lineTo(28,-20);ctx.lineTo(44,-5);ctx.closePath();ctx.fill();ctx.fillStyle='#26eaff55';ctx.fillRect(-10,-15,30,9);ctx.fillStyle='#fff';ctx.fillRect(56,5,13,4);ctx.fillRect(-69,6,13,4);ctx.fillStyle='#050509';ctx.fillRect(-60,23,27,12);ctx.fillRect(35,23,27,12);if(player){ctx.fillStyle='#ff405f';ctx.fillRect(-54,4,11,5);ctx.fillRect(43,4,11,5)}ctx.restore()}
function palm(x,y,s,flip){ctx.save();ctx.translate(x,y);ctx.scale(flip?-s:s,s);ctx.strokeStyle='#10101b';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(10,-90,25,-190);ctx.stroke();ctx.fillStyle='#171222';for(let i=0;i<7;i++){ctx.save();ctx.translate(25,-190);ctx.rotate(i*Math.PI/3.5);ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(35,-10,80,-5);ctx.quadraticCurveTo(45,15,0,5);ctx.fill();ctx.restore()}ctx.restore()}
function draw(t){let w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);let g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#03040a');g.addColorStop(.42,'#171027');g.addColorStop(.64,'#54153f');g.addColorStop(1,'#08070e');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);let gl=ctx.createRadialGradient(w*.5,h*.5,5,w*.5,h*.5,w*.55);gl.addColorStop(0,'#ff2f9e66');gl.addColorStop(1,'#ff2f9e00');ctx.fillStyle=gl;ctx.fillRect(0,h*.3,w,h*.45);for(let x=0;x<w;x+=48){let bh=45+x*17%105;ctx.fillStyle='#090a12';ctx.fillRect(x,h*.46-bh,34,bh);if(x%96===0){ctx.fillStyle='#20e5ff99';ctx.fillRect(x+8,h*.46-bh+14,4,12);ctx.fillStyle='#ff2f9eaa';ctx.fillRect(x+18,h*.46-bh+33,4,8)}}palm(w*.1,h*.75,1,false);palm(w*.9,h*.75,1,true);ctx.fillStyle='#08080d';ctx.beginPath();ctx.moveTo(w*.34,h*.46);ctx.lineTo(w*.66,h*.46);ctx.lineTo(w*.97,h);ctx.lineTo(w*.03,h);ctx.closePath();ctx.fill();ctx.strokeStyle='#ffffff25';ctx.beginPath();ctx.moveTo(w*.34,h*.46);ctx.lineTo(w*.03,h);ctx.moveTo(w*.66,h*.46);ctx.lineTo(w*.97,h);ctx.stroke();let off=t/6%150;for(let y=h*.5-off;y<h;y+=150){let f=(y-h*.46)/(h*.54);ctx.fillStyle='#ffffff55';ctx.fillRect(w*.5-2,y,4+f*6,45+f*90)}for(let s of[-1,1])for(let i=0;i<10;i++){let y=h*.48+i*60+t/20%60,f=(y-h*.46)/(h*.54),x=w*.5+s*(w*.16+f*w*.35);ctx.fillStyle=i%2?'#ff2f9e99':'#20e5ff99';ctx.fillRect(x,y,4+f*7,3+f*5)}let rx=w*.63-(S.player-S.rival)*.06,ry=h*.68-Math.min(105,S.rival*.1);car(rx,ry,.72,rivals[(S.level-1)%4][2],false);car(w*.42,h*.73,1,cars[S.car][2],true)}
function hud(){let p=Math.min(100,S.player/1.9),r=Math.min(100,S.rival/1.9);$('rpmValue').textContent=(4.8+S.rpm*.052).toFixed(1);$('rpmBar').style.width=S.rpm+'%';$('gearValue').textContent=S.gear;$('distanceValue').textContent=Math.min(400,Math.round(S.player*2.1))+' M';$('playerProgress').style.width=p+'%';$('rivalProgress').style.width=r+'%';$('rpmNeedle').style.transform=`rotate(${-125+S.rpm*2.5}deg)`;$('speedNeedle').style.transform=`rotate(${-125+p*2.5}deg)`;$('boostNeedle').style.transform=`rotate(${-125+S.nitro*2.5}deg)`}
function loop(t){requestAnimationFrame(loop);if(!$('race').classList.contains('active'))return;draw(t);if(!S.running){last=t;return}let dt=Math.min(.035,(t-last)/1000||0);last=t;S.time+=dt;S.rpm=Math.min(100,S.rpm+dt*(31+S.gear*6));S.player+=dt*(3.1+S.gear*.65);S.rival+=dt*(3.65+S.level*.035);if(S.nitro>0)S.nitro=Math.max(0,S.nitro-dt*.8);hud();if(S.player>=190||S.rival>=190)finish()}
function finish(){if(!S.running)return;S.running=false;let win=S.player>=S.rival,reward=win?750:250;S.credits+=reward;$('credits').textContent=S.credits;$('resultKicker').textContent=win?'LEVEL COMPLETE':'RUN COMPLETE';$('resultTitle').innerHTML=win?'CLEAN<br><em>GETAWAY.</em>':'THE RIVAL<br><em>GOT YOU.</em>';$('resultTime').textContent=S.time.toFixed(2).padStart(5,'0');$('resultPlace').textContent=win?'1ST':'2ND';$('resultReward').textContent='+'+reward+' CR';$('resultShift').textContent='× '+S.perfect;show('result')}
$('raceBtn').onclick=startRace;$('garageBtn').onclick=()=>{show('garage');selectCar(S.car)};$('nextBtn').onclick=()=>{if(S.level<16)S.level++;startRace()};$('nitroBtn').onclick=nitro;$('shiftZone').onclick=shift;$('soundBtn').onclick=()=>{$('soundBtn').textContent=$('soundBtn').textContent==='♫'?'×':'♫'};document.onkeydown=e=>{if(e.code==='Space'){e.preventDefault();shift()}if(e.key.toLowerCase()==='n')nitro()};renderCars();selectCar(0);resize();addEventListener('resize',resize);requestAnimationFrame(loop);
